pipeline {
    agent any 
    stages {
        stage('Npm install'){
            steps{
                sh '''
                cd /home/ec2-user/.jenkins/workspace/ang_clone/angularTest
                rm -rf /node_modules/
                npm i
                '''
            }
        }
        stage('Build') { ?
          steps {
                sh '''
                cd /home/ec2-user/.jenkins/workspace/ang_clone/angularTest
                ng build
                '''
          }
        }
        stage('Test'){
            steps{
                sh '''
                cd /home/ec2-user/.jenkins/workspace/ang_clone/angularTest
                npm run test
                '''
            }
        }
        stage('Deploy'){
            steps{
                sh '''
                cd /home/ec2-user/.jenkins/workspace/ang_clone/angularTest
                 aws2 s3 cp --recursive ./dist s3://ui-core/angular
                '''
            }
        }
    }
}