pipeline {
    agent any 
    stages {
        stage('npm install') {
            steps {
                sh 'echo "Installing node_modules"'
                sh '''
                cd /home/ec2-user/.jenkins/workspace/Angular_Trial_Test_Stage_master/angularTest
                npm install
                '''
            }
        }
        stage('Build') {
          steps {
                sh '''
                cd /home/ec2-user/.jenkins/workspace/Angular_Trial_Test_Stage_master/angularTest
                ng build
                '''
          }
        }
        stage('Deploy'){
            steps{
                sh '''
                cd /home/ec2-user/.jenkins/workspace/Angular_Trial_Test_Stage_master/angularTest
                 aws s3 cp --recursive ./dist s3://ui-core/angular
                '''
            }
        }
    }
}